### PR TITLE
Add tests for useFormal

### PR DESCRIPTION
**Pull request by the-bionic**
There is no support in `react-hooks-testing-library` for testing async code. `submit` and `validate` were not tested. `utils` also need some testing as well. What do you think about what I have so far?

### CODE REVIEW

**Comment by kevinwolfcr** [comment]
Hi, @the-bionic, thanks for the tests, coverage was increased by 45% 😍🔝

Now, although the tests are working, I was thinking about other structure to define them (my bad here, since I didn't put test placeholders).

Since every property returned by `useFormal()` change its value, I think it makes more sense to `describe()` them and then `test()` every possible state.

I put the placeholders on 69806bdb5e68d5a96bbba186adc16a0ef9486c7a, so you can just update your fork and add the tests there.

Thanks again!

**Comment by kevinwolfcr** [comment]
**PD: I've changed the PR title, because there is no need to follow the conventional commits since I put that commit message once I squash merge the PR into master.**

**Comment by kevinwolfcr** [comment]
@the-bionic I've accidentally closed the PR. Can you reopen please?

**Comment by the-bionic** [comment]
@kevinwolfcr I'm unable to reopen the PR.

**Comment by the-bionic** [comment]
```
Since every property returned by useFormal() change its value, I think it makes more sense to describe() them and then test() every possible state.
```
I got a warning on the console stating: 

```
 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and as
ynchronous tasks in a useEffect cleanup function.
        in TestHook
``` 

I think since the tests are being unmounted after each test case: ```afterEach(cleanup)```. Using a single instance in ```describe()``` and modifying its state does not work. So, one ```useFormal()``` for each test case works. What do you think?

**Pull request closed without merging**
