### PR TITLE
Add advanced validation recipe

### PR DESCRIPTION
**Pull request by kecoco16**
Improve validation in storybook examples to prevent unexpected data format.

image
image

### CODE REVIEW

**Comment by kevinwolfcr** [comment]
Nice, it improved the validation. But we really need that level of details on the documentation? Thinking of this is more focused on the form validation working rather than the validation declaration.

**Comment by kecoco16** [comment]
I thing that is important for the DE, the first thing i did when i watching the examples was try them and i see this details on the validation so maybe this is more like a real world example but of course i understand the idea of keep them simples.

**Comment by kevinwolfcr** [comment]
Yes. I agree that it makes more sense to put this into a single "more advanced" recipe rather than updating all the examples.

Maybe you can create an "advanced validation" recipe and add some explanation on the README. It can be at `.storybook/recipes/advanced-validation`.

Now that we will start showing recipes on the storybook, it makes sense to update `.storybook/stories.ts` and prepend either `examples` or `recipes` to the path at `createStory`:

```typescript
createStory('Examples', 'Basic', 'examples/basic'),
// ... other stories
createStory('Recipes', 'Advanced validation', 'recipes/advanced-validation'),
```

**Comment by kevinwolfcr** [comment]
**PD: I've changed the PR title, because there is no need to follow the conventional commits since I put that commit message once I squash merge the PR into master.**

**Comment by kevinwolfcr** [comment]
@kecoco16  I've accidentally closed the PR. Can you reopen please?

**Pull request closed without merging**
